InventoryManagementSystem1/Controllers/CategoriesController.cs
using InventoryManagementSystem1.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace InventoryManagementSystem1.Controllers
{
    public class CategoriesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CategoriesController(ApplicationDbContext context)
        {
            _context = context;
        }

      
        public async Task<IActionResult> Index()
        {
            return View(await _context.Categories.ToListAsync());
        }

       
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Category category)
        {
            if (ModelState.IsValid)
            {
               
                category.CategoryID = Guid.NewGuid();

                _context.Categories.Add(category);
                _context.SaveChanges();

         
                TempData["success"] = "Category added successfully!";

                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

     
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
                return NotFound();

            var category = await _context.Categories.FindAsync(id);
            return View(category);
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, Category category)
        {
            if (id != category.CategoryID)
                return NotFound();

            if (ModelState.IsValid)
            {
                _context.Update(category);
                await _context.SaveChangesAsync();

          
                TempData["success"] = "Category updated successfully!";

                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

     
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
                return NotFound();

            var category = await _context.Categories
                .FirstOrDefaultAsync(m => m.CategoryID == id);

            return View(category);
        }

      
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var category = await _context.Categories.FindAsync(id);

            if (category != null)
            {
                _context.Categories.Remove(category);
                await _context.SaveChangesAsync();

                
                TempData["success"] = "Category deleted successfully!";
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

InventoryManagementSystem1/Controllers/ProductsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using InventoryManagementSystem1.Models;

namespace InventoryManagementSystem1.Controllers
{
    public class ProductsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ProductsController(ApplicationDbContext context)
        {
            _context = context;
        }

       
        public async Task<IActionResult> Index(
     string searchString,
     Guid? categoryId,
     Guid? supplierId)
        {
        
            ViewBag.Categories = _context.Categories.ToList();
            ViewBag.Suppliers = _context.Suppliers.ToList();

            var products = _context.Products
                .Include(p => p.Category)
                .Include(p => p.Supplier)
                .AsQueryable();

         
            if (!string.IsNullOrEmpty(searchString))
            {
                products = products.Where(p =>
                    p.ProductName.Contains(searchString));
            }

  
            if (categoryId.HasValue)
            {
                products = products.Where(p =>
                    p.CategoryID == categoryId);
            }

      
            if (supplierId.HasValue)
            {
                products = products.Where(p =>
                    p.SupplierID == supplierId);
            }

            return View(await products.ToListAsync());
        }


     
        public IActionResult Create()
        {
            ViewData["CategoryID"] =
                new SelectList(_context.Categories, "CategoryID", "CategoryName");

            ViewData["SupplierID"] =
                new SelectList(_context.Suppliers, "SupplierID", "SupplierName");

            return View();
        }



        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Product product)
        {
            if (!ModelState.IsValid)
            {
                
                foreach (var state in ModelState)
                {
                    foreach (var error in state.Value.Errors)
                    {
                        Console.WriteLine($"{state.Key} : {error.ErrorMessage}");
                    }
                }
            }

            if (ModelState.IsValid)
            {
                product.ProductID = Guid.NewGuid();
                _context.Products.Add(product);
                await _context.SaveChangesAsync();

           
                TempData["success"] = "Product added successfully!";

                return RedirectToAction(nameof(Index));
            }


            ViewData["CategoryID"] =
                new SelectList(_context.Categories, "CategoryID", "CategoryName", product.CategoryID);

            ViewData["SupplierID"] =
                new SelectList(_context.Suppliers, "SupplierID", "SupplierName", product.SupplierID);

            return View(product);
        }



        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
                return NotFound();

            var product = await _context.Products.FindAsync(id);
            if (product == null)
                return NotFound();

            ViewData["CategoryID"] =
                new SelectList(_context.Categories, "CategoryID", "CategoryName", product.CategoryID);

            ViewData["SupplierID"] =
                new SelectList(_context.Suppliers, "SupplierID", "SupplierName", product.SupplierID);

            return View(product);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, Product product)
        {
            if (id != product.ProductID)
                return NotFound();

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(product);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductExists(product.ProductID))
                        return NotFound();
                    else
                        throw;
                }
                return RedirectToAction(nameof(Index));
            }

            ViewData["CategoryID"] =
                new SelectList(_context.Categories, "CategoryID", "CategoryName", product.CategoryID);

            ViewData["SupplierID"] =
                new SelectList(_context.Suppliers, "SupplierID", "SupplierName", product.SupplierID);

            return View(product);
        }

       
        public async Task<IActionResult> Delete(Guid id)
        {
            var product = await _context.Products
                .Include(p => p.Category)
                .Include(p => p.Supplier)
                .FirstOrDefaultAsync(p => p.ProductID == id);

            if (product == null)
                return NotFound();

            return View(product);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var product = await _context.Products.FindAsync(id);

            if (product != null)
            {
                _context.Products.Remove(product);
                await _context.SaveChangesAsync();

                TempData["success"] = "Product deleted successfully!";
            }

            return RedirectToAction(nameof(Index));
        }



        private bool ProductExists(Guid id)
        {
            return _context.Products.Any(e => e.ProductID == id);
        }
    }
}

InventoryManagementSystem1/Controllers/SuppliersController.cs
using InventoryManagementSystem1.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace InventoryManagementSystem.Controllers
{
    public class SuppliersController : Controller
    {
        private readonly ApplicationDbContext _context;

        public SuppliersController(ApplicationDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var suppliers = await _context.Suppliers.ToListAsync();
            return View(suppliers);
        }

       
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Supplier supplier)
        {
            if (ModelState.IsValid)
            {
                supplier.SupplierID = Guid.NewGuid();
                _context.Suppliers.Add(supplier);
                await _context.SaveChangesAsync();

               
                TempData["success"] = "Supplier added successfully!";

                return RedirectToAction(nameof(Index));
            }

            return View(supplier);
        }

        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
                return NotFound();

            var supplier = await _context.Suppliers.FindAsync(id);
            if (supplier == null)
                return NotFound();

            return View(supplier);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, Supplier supplier)
        {
            if (id != supplier.SupplierID)
                return NotFound();

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(supplier);
                    await _context.SaveChangesAsync();

         
                    TempData["success"] = "Supplier updated successfully!";
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SupplierExists(supplier.SupplierID))
                        return NotFound();
                    else
                        throw;
                }
                return RedirectToAction(nameof(Index));
            }
            return View(supplier);
        }


        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
                return NotFound();

            var supplier = await _context.Suppliers
                .FirstOrDefaultAsync(m => m.SupplierID == id);

            if (supplier == null)
                return NotFound();

            return View(supplier);
        }


        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var supplier = await _context.Suppliers.FindAsync(id);
            if (supplier != null)
            {
                _context.Suppliers.Remove(supplier);
                await _context.SaveChangesAsync();

  
                TempData["success"] = "Supplier deleted successfully!";
            }
            return RedirectToAction(nameof(Index));
        }

        private bool SupplierExists(Guid id)
        {
            return _context.Suppliers.Any(e => e.SupplierID == id);
        }
    }
}

InventoryManagementSystem1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - InventoryManagementSystem</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/InventoryManagementSystem1.styles.css" asp-append-version="true" />
    <link href="https://fonts.googleapis.com/css2?family=Pacifico&display=swap" rel="stylesheet">
</head>

<body>

    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary shadow-sm">
            <div class="container-fluid">

                <a class="navbar-brand d-flex align-items-center gap-2"
                   asp-controller="Home"
                   asp-action="Index">
                    <img src="~/Image/Digitalwold1.png" alt="Digital Wold Logo" height="60" />
                    <span class="fw-bold text-white">Digital Wold</span>
                </a>

                <button class="navbar-toggler"
                        type="button"
                        data-bs-toggle="collapse"
                        data-bs-target="#mainNavbar">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="mainNavbar">
                    <ul class="navbar-nav ms-auto">

                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Products" asp-action="Index">Products</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Categories" asp-action="Index">Category</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Suppliers" asp-action="Index">Supplier</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <main class="container py-4">
        @RenderBody()
    </main>


    <footer class="footer mt-5 py-3"> 
        <div class="container-fluid d-flex justify-content-between align-items-center"> 
            <span class="text-muted ps-3"> © 2026 Inventory System </span> 
            <a class="text-muted pe-3" asp-controller="Home" asp-action="Privacy">
                Privacy 
             </a> 
        </div> 
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>